### ISSUE TITLE
Man, Software...

### ISSUE THREAD

**Issue by nibalizer** [sdague/probot-testing#18]
Am I right?
![grafeas](https://user-images.githubusercontent.com/195179/32954800-bf64e2fc-cb79-11e7-8f0f-8f907b18a221.png)

**Comment by sdague** [comment]
I really appreciate finding out how people are using this software in
the wide world, and people taking the time to report issues when they
find them.

I only get a chance to work on this project on the weekends, so please
be patient as it takes time to get around to looking into the issues
in depth.
